#!/bin/bash

# Copyright (c) 2024 Bima Kharisma Wicaksana
# GitHub: https://github.com/bimakw
#
# Bootstrap script for Terraform GCS Backend
# This script creates the GCS bucket for storing Terraform state

set -euo pipefail

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# Default values
DEFAULT_REGION="asia-southeast2"
DEFAULT_STORAGE_CLASS="STANDARD"

# Functions
log_info() {
    echo -e "${GREEN}[INFO]${NC} $1"
}

log_warn() {
    echo -e "${YELLOW}[WARN]${NC} $1"
}

log_error() {
    echo -e "${RED}[ERROR]${NC} $1"
}

usage() {
    cat << EOF
Usage: $0 [OPTIONS]

Bootstrap Terraform GCS Backend for state storage.

OPTIONS:
    -p, --project       GCP Project ID (required)
    -r, --region        GCP Region (default: ${DEFAULT_REGION})
    -e, --environment   Environment name (dev/staging/prod)
    -h, --help          Show this help message

EXAMPLES:
    $0 -p my-project-id -e dev
    $0 --project my-project-id --region us-central1 --environment prod

EOF
    exit 0
}

# Parse arguments
PROJECT_ID=""
REGION="${DEFAULT_REGION}"
ENVIRONMENT=""

while [[ $# -gt 0 ]]; do
    case $1 in
        -p|--project)
            PROJECT_ID="$2"
            shift 2
            ;;
        -r|--region)
            REGION="$2"
            shift 2
            ;;
        -e|--environment)
            ENVIRONMENT="$2"
            shift 2
            ;;
        -h|--help)
            usage
            ;;
        *)
            log_error "Unknown option: $1"
            usage
            ;;
    esac
done

# Validate required arguments
if [[ -z "${PROJECT_ID}" ]]; then
    log_error "Project ID is required"
    usage
fi

if [[ -z "${ENVIRONMENT}" ]]; then
    log_error "Environment is required"
    usage
fi

# Validate environment
if [[ ! "${ENVIRONMENT}" =~ ^(dev|staging|prod)$ ]]; then
    log_error "Environment must be one of: dev, staging, prod"
    exit 1
fi

# Bucket name follows GCS naming conventions
BUCKET_NAME="${PROJECT_ID}-terraform-state"

log_info "Bootstrapping Terraform Backend"
log_info "Project ID: ${PROJECT_ID}"
log_info "Region: ${REGION}"
log_info "Environment: ${ENVIRONMENT}"
log_info "Bucket Name: ${BUCKET_NAME}"

# Check if gcloud is installed
if ! command -v gcloud &> /dev/null; then
    log_error "gcloud CLI is not installed. Please install it first."
    exit 1
fi

# Set project
log_info "Setting GCP project..."
gcloud config set project "${PROJECT_ID}"

# Enable required APIs
log_info "Enabling required APIs..."
gcloud services enable storage.googleapis.com --quiet

# Check if bucket exists
if gsutil ls -b "gs://${BUCKET_NAME}" &> /dev/null; then
    log_warn "Bucket ${BUCKET_NAME} already exists"
else
    # Create bucket
    log_info "Creating GCS bucket..."
    gsutil mb -p "${PROJECT_ID}" -l "${REGION}" -c "${DEFAULT_STORAGE_CLASS}" "gs://${BUCKET_NAME}"

    # Enable versioning
    log_info "Enabling versioning..."
    gsutil versioning set on "gs://${BUCKET_NAME}"

    # Set uniform bucket-level access
    log_info "Setting uniform bucket-level access..."
    gsutil uniformbucketlevelaccess set on "gs://${BUCKET_NAME}"

    # Set lifecycle rules (delete old versions after 30 days)
    log_info "Setting lifecycle rules..."
    cat > /tmp/lifecycle.json << 'EOF'
{
  "lifecycle": {
    "rule": [
      {
        "action": {"type": "Delete"},
        "condition": {
          "numNewerVersions": 5,
          "isLive": false
        }
      }
    ]
  }
}
EOF
    gsutil lifecycle set /tmp/lifecycle.json "gs://${BUCKET_NAME}"
    rm /tmp/lifecycle.json

    log_info "Bucket ${BUCKET_NAME} created successfully"
fi

# Generate backend configuration
BACKEND_CONFIG_FILE="terraform/environments/${ENVIRONMENT}/backend.tf"
log_info "Generating backend configuration at ${BACKEND_CONFIG_FILE}..."

cat > "${BACKEND_CONFIG_FILE}" << EOF
# Auto-generated by bootstrap-backend.sh
# Do not edit manually

terraform {
  backend "gcs" {
    bucket = "${BUCKET_NAME}"
    prefix = "terraform/state/${ENVIRONMENT}"
  }
}
EOF

log_info "Backend configuration generated"

# Print next steps
echo ""
log_info "Bootstrap completed successfully!"
echo ""
echo "Next steps:"
echo "  1. Navigate to the environment directory:"
echo "     cd terraform/environments/${ENVIRONMENT}"
echo ""
echo "  2. Initialize Terraform with the new backend:"
echo "     terraform init"
echo ""
echo "  3. If migrating existing state, run:"
echo "     terraform init -migrate-state"
echo ""
